<?php

return [
    // Assets Control System
    'assets_control' => 'Assets Control System',
    'assets_dashboard' => 'Assets Dashboard',
    'assets' => 'Assets',
    'asset_categories' => 'Asset Categories',
    'asset_locations' => 'Asset Locations',
    'asset_assignments' => 'Asset Assignments',
    'asset_logs' => 'Asset Logs',
    
    // Assets
    'add_asset' => 'Add Asset',
    'create_asset' => 'Create Asset',
    'edit_asset' => 'Edit Asset',
    'delete_asset' => 'Delete Asset',
    'view_asset' => 'View Asset',
    'asset_code' => 'Asset Code',
    'barcode' => 'Barcode',
    'serial_number' => 'Serial Number',
    'purchase_date' => 'Purchase Date',
    'warranty_expiry' => 'Warranty Expiry',
    'cost' => 'Cost',
    'location' => 'Location',
    'assigned_to' => 'Assigned To',
    'category' => 'Category',
    'status' => 'Status',
    'name' => 'Name',
    'unassigned' => 'Unassigned',
    'active' => 'Active',
    'maintenance' => 'Maintenance',
    'retired' => 'Retired',
    'print_barcode' => 'Print Barcode',
    'download_barcode' => 'Download Barcode',
    'barcode_image' => 'Barcode Image',
    
    // Inventory Status
    'in_stock' => 'In Stock',
    'out_of_stock' => 'Out of Stock',
    'low_stock' => 'Low Stock',
    'reserved' => 'Reserved',
    'damaged' => 'Damaged',
    'expired' => 'Expired',
    
    // Categories
    'add_category' => 'Add Category',
    'create_category' => 'Create Category',
    'edit_category' => 'Edit Category',
    'delete_category' => 'Delete Category',
    'view_category' => 'View Category',
    'category_properties' => 'Category Properties',
    'add_property' => 'Add Property',
    'edit_property' => 'Edit Property',
    'delete_property' => 'Delete Property',
    'property_name' => 'Property Name',
    'property_type' => 'Property Type',
    'property_required' => 'Required',
    'property_optional' => 'Optional',
    'property_options' => 'Property Options',
    'property_sort_order' => 'Sort Order',
    'text' => 'Text',
    'number' => 'Number',
    'date' => 'Date',
    'select' => 'Select',
    'boolean' => 'Boolean',
    'image' => 'Image',
    'options' => 'Options',
    'options_placeholder' => 'Enter one option per line',
    'options_help' => 'Enter each option on a separate line',
    'select_type' => 'Select Type',
    'select_option' => 'Select Option',
    'required' => 'Required',
    'optional' => 'Optional',
    
    // Locations
    'add_location' => 'Add Location',
    'create_location' => 'Create Location',
    'edit_location' => 'Edit Location',
    'delete_location' => 'Delete Location',
    'view_location' => 'View Location',
    'no_address' => 'No Address',
    
    // Assignments
    'assign_asset' => 'Assign Asset',
    'return_asset' => 'Return Asset',
    'assignment_history' => 'Assignment History',
    'assigned_date' => 'Assigned Date',
    'returned_date' => 'Returned Date',
    'assigned_by' => 'Assigned By',
    'currently_assigned' => 'Currently Assigned',
    'not_returned' => 'Not Returned',
    'assignment_notes' => 'Assignment Notes',
    'assignment_notes_placeholder' => 'Enter notes about the asset assignment...',
    
    // Logs
    'action' => 'Action',
    'actions' => 'Actions',
    'all_actions' => 'All Actions',
    'assigned' => 'Assigned',
    'returned' => 'Returned',
    'created' => 'Created',
    'updated' => 'Updated',
    'assigned' => 'Assigned',
    'returned' => 'Returned',
    'moved' => 'Moved',
    'repaired' => 'Repaired',
    'disposed' => 'Disposed',
    'date_from' => 'From Date',
    'date_to' => 'To Date',
    'no_notes' => 'No Notes',
    'by' => 'By',
    'user' => 'User',
    'notes' => 'Notes',
    
    // Dashboard
    'total_assets' => 'Total Assets',
    'active_assets' => 'Active Assets',
    'maintenance_assets' => 'Maintenance Assets',
    'retired_assets' => 'Retired Assets',
    'assigned_assets' => 'Assigned Assets',
    'unassigned_assets' => 'Unassigned Assets',
    'assets_by_category' => 'Assets by Category',
    'assets_by_location' => 'Assets by Location',
    'recent_assignments' => 'Recent Assignments',
    'recent_activity' => 'Recent Activity',
    'warranty_expiring_soon' => 'Warranty Expiring Soon',
    'days_remaining' => 'Days Remaining',
    'days' => 'Days',
    'expired' => 'Expired',
    'view_all' => 'View All',
    'no_recent_assignments' => 'No Recent Assignments',
    'no_recent_activity' => 'No Recent Activity',
    'refresh' => 'Refresh',
    
    // Filters and Search
    'search_assets' => 'Search Assets',
    'all_categories' => 'All Categories',
    'all_statuses' => 'All Statuses',
    'all_locations' => 'All Locations',
    'all_users' => 'All Users',
    'all_assets' => 'All Assets',
    'filter' => 'Filter',
    
    // Status and Actions
    'inactive' => 'Inactive',
    'activate' => 'Activate',
    'deactivate' => 'Deactivate',
    'return' => 'Return',
    'assign' => 'Assign',
    'move' => 'Move',
    'repair' => 'Repair',
    'dispose' => 'Dispose',
    
    // Messages
    'asset_created_successfully' => 'Asset created successfully',
    'asset_updated_successfully' => 'Asset updated successfully',
    'asset_deleted_successfully' => 'Asset deleted successfully',
    'asset_assigned_successfully' => 'Asset assigned successfully',
    'asset_returned_successfully' => 'Asset returned successfully',
    'category_created_successfully' => 'Category created successfully',
    'category_updated_successfully' => 'Category updated successfully',
    'category_deleted_successfully' => 'Category deleted successfully',
    'location_created_successfully' => 'Location created successfully',
    'location_updated_successfully' => 'Location updated successfully',
    'location_deleted_successfully' => 'Location deleted successfully',
    'property_added_successfully' => 'Property added successfully',
    'property_updated_successfully' => 'Property updated successfully',
    'property_deleted_successfully' => 'Property deleted successfully',
    
    // Errors
    'no_assets_found' => 'No Assets Found',
    'no_assets_description' => 'No assets found matching your search criteria',
    'add_first_asset' => 'Add First Asset',
    'no_categories_found' => 'No Categories Found',
    'no_categories_description' => 'No asset categories found',
    'add_first_category' => 'Add First Category',
    'no_locations_found' => 'No Locations Found',
    'no_locations_description' => 'No asset locations found',
    'add_first_location' => 'Add First Location',
    'no_assignments_found' => 'No Assignments Found',
    'no_assignments_description' => 'No asset assignments found',
    'create_first_assignment' => 'Create First Assignment',
    'no_logs_found' => 'No Logs Found',
    'no_logs_description' => 'No asset logs found',
    'asset_not_found' => 'Asset Not Found',
    'error_loading_asset' => 'Error Loading Asset',
    'error_loading_properties' => 'Error Loading Properties',
    'barcode_image_not_found' => 'Barcode Image Not Found',
    'no_properties_defined' => 'No Properties Defined',
    'add_properties_description' => 'Add custom properties for this category',
    'add_first_property' => 'Add First Property',
    'no_assets_in_category' => 'No Assets in Category',
    'no_assets_in_category_description' => 'No assets have been added to this category yet',
    'no_assignment_history' => 'No Assignment History',
    'no_data_available' => 'No Data Available',
    
    // Confirmations
    'confirm_delete' => 'Are you sure you want to delete?',
    'confirm_delete_asset' => 'Are you sure you want to delete this asset?',
    'confirm_delete_category' => 'Are you sure you want to delete this category?',
    'confirm_delete_location' => 'Are you sure you want to delete this location?',
    'confirm_delete_property' => 'Are you sure you want to delete this property?',
    'confirm_return_asset' => 'Are you sure you want to return this asset?',
    'confirm_delete_category_with_assets' => 'Cannot delete category with existing assets',
    'confirm_delete_location_with_assets' => 'Cannot delete location with existing assets',
    
    // Help and Tips
    'help' => 'Help',
    'category_help_title' => 'Category Help',
    'category_help_description' => 'Categories help organize assets by type or purpose.',
    'properties_help_title' => 'Properties Help',
    'properties_help_description' => 'Custom properties allow storing additional information for each asset.',
    'property_types' => 'Property Types',
    'text_description' => 'Free text input',
    'number_description' => 'Numeric input',
    'date_description' => 'Date picker',
    'select_description' => 'Dropdown list',
    'boolean_description' => 'Yes/No selection',
    'image_description' => 'Image upload',
    'location_help_title' => 'Location Help',
    'location_help_description' => 'Locations represent physical places where assets are stored.',
    'examples' => 'Examples',
    'office_building' => 'Office Building',
    'warehouse' => 'Warehouse',
    'lab' => 'Laboratory',
    'server_room' => 'Server Room',
    'workshop' => 'Workshop',
    'tips' => 'Tips',
    'location_tip_1' => 'Use clear and specific names for locations',
    'location_tip_2' => 'Include complete address information',
    'location_tip_3' => 'Update locations when they change',
    'assignment_help_title' => 'Assignment Help',
    'assignment_help_description' => 'Assignments link assets to employees responsible for them.',
    'assignment_rules' => 'Assignment Rules',
    'assignment_rule_1' => 'One asset cannot be assigned to multiple employees at the same time',
    'assignment_rule_2' => 'Assignment date must be recorded',
    'assignment_rule_3' => 'Notes can be added about the assignment',
    'assignment_rule_4' => 'Who made the assignment must be recorded',
    'notes_tips' => 'Notes Tips',
    'notes_tip_1' => 'Write clear and useful notes',
    'notes_tip_2' => 'Include reason for assignment or return',
    'notes_tip_3' => 'Update notes when needed',
    
    // Quick Actions
    'quick_actions' => 'Quick Actions',
    'add_asset_to_category' => 'Add Asset to Category',
    'view_all_assets' => 'View All Assets',
    'view_all_history' => 'View All History',
    'view_all_activity' => 'View All Activity',
    'edit_category' => 'Edit Category',
    'edit_location' => 'Edit Location',
    'edit_asset' => 'Edit Asset',
    
    // Statistics
    'quick_stats' => 'Quick Stats',
    'total_categories' => 'Total Categories',
    'total_locations' => 'Total Locations',
    'total_assignments' => 'Total Assignments',
    'active_assignments' => 'Active Assignments',
    'available_assets' => 'Available Assets',
    'total_users' => 'Total Users',
    'assets_count' => 'Assets Count',
    'properties_count' => 'Properties Count',
    'percentage' => 'Percentage',
    'count' => 'Count',
    
    // Navigation
    'back_to_assets' => 'Back to Assets',
    'back_to_categories' => 'Back to Categories',
    'back_to_locations' => 'Back to Locations',
    'back_to_assignments' => 'Back to Assignments',
    'back_to_logs' => 'Back to Logs',
    
    // Form Labels
    'select_category' => 'Select Category',
    'select_location' => 'Select Location',
    'select_user' => 'Select User',
    'select_asset' => 'Select Asset',
    'basic_information' => 'Basic Information',
    'additional_information' => 'Additional Information',
    'category_information' => 'Category Information',
    'asset_information' => 'Asset Information',
    'location_information' => 'Location Information',
    'assignment_information' => 'Assignment Information',
    'asset_details' => 'Asset Details',
    'no_description' => 'No Description',
    'not_specified' => 'Not Specified',
    'no_image' => 'No Image',
    
    // Print
    'print' => 'Print',
    'download' => 'Download',
    'printed_on' => 'Printed On',
    
    // Miscellaneous
    'loading' => 'Loading...',
    'yes' => 'Yes',
    'no' => 'No',
    'cancel' => 'Cancel',
    'save' => 'Save',
    'create' => 'Create',
    'update' => 'Update',
    'delete' => 'Delete',
    'edit' => 'Edit',
    'view' => 'View',
    'search' => 'Search',
    'export' => 'Export',
    'import' => 'Import',
    'refresh' => 'Refresh',
    'close' => 'Close',
    'open' => 'Open',
    'show' => 'Show',
    'hide' => 'Hide',
    'expand' => 'Expand',
    'collapse' => 'Collapse',
    'more' => 'More',
    'less' => 'Less',
    'all' => 'All',
    'none' => 'None',
    'select_all' => 'Select All',
    'deselect_all' => 'Deselect All',
    'clear' => 'Clear',
    'reset' => 'Reset',
    'apply' => 'Apply',
    'submit' => 'Submit',
    'continue' => 'Continue',
    'finish' => 'Finish',
    'next' => 'Next',
    'previous' => 'Previous',
    'first' => 'First',
    'last' => 'Last',
    'page' => 'Page',
    'of' => 'of',
    'items' => 'Items',
    'per_page' => 'Per Page',
    'showing' => 'Showing',
    'to' => 'to',
    'from' => 'from',
    'results' => 'Results',
    'no_results' => 'No Results',
    'no_results_found' => 'No Results Found',
    'try_again' => 'Try Again',
    'error_occurred' => 'An Error Occurred',
    'success_message' => 'Success',
    'error_message' => 'Error',
    'warning_message' => 'Warning',
    'info_message' => 'Info',
    'confirm_message' => 'Confirm',
    'are_you_sure' => 'Are you sure?',
    'this_action_cannot_be_undone' => 'This action cannot be undone',
    'please_confirm' => 'Please confirm',
    'please_wait' => 'Please wait',
    'processing' => 'Processing',
    'completed' => 'Completed',
    'failed' => 'Failed',
    'pending' => 'Pending',
    'in_progress' => 'In Progress',
    'cancelled' => 'Cancelled',
    'approved' => 'Approved',
    'rejected' => 'Rejected',
    'draft' => 'Draft',
    'published' => 'Published',
    'archived' => 'Archived',
    'deleted' => 'Deleted',
    'restored' => 'Restored',
    'updated' => 'Updated',
    'created' => 'Created',
    'modified' => 'Modified',
    'changed' => 'Changed',
    'added' => 'Added',
    'removed' => 'Removed',
    'enabled' => 'Enabled',
    'disabled' => 'Disabled',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'online' => 'Online',
    'offline' => 'Offline',
    'available' => 'Available',
    'unavailable' => 'Unavailable',
    'public' => 'Public',
    'private' => 'Private',
    'shared' => 'Shared',
    'personal' => 'Personal',
    'work' => 'Work',
    'home' => 'Home',
    'office' => 'Office',
    'mobile' => 'Mobile',
    'landline' => 'Landline',
    'email' => 'Email',
    'phone' => 'Phone',
    'address' => 'Address',
    'city' => 'City',
    'country' => 'Country',
    'zip_code' => 'Zip Code',
    'postal_code' => 'Postal Code',
    'state' => 'State',
    'province' => 'Province',
    'region' => 'Region',
    'district' => 'District',
    'street' => 'Street',
    'building' => 'Building',
    'floor' => 'Floor',
    'room' => 'Room',
    'apartment' => 'Apartment',
    'unit' => 'Unit',
    'block' => 'Block',
    'plot' => 'Plot',
    'landmark' => 'Landmark',
    'coordinates' => 'Coordinates',
    'latitude' => 'Latitude',
    'longitude' => 'Longitude',
    'altitude' => 'Altitude',
    'timezone' => 'Timezone',
    'language' => 'Language',
    'currency' => 'Currency',
    'date_format' => 'Date Format',
    'time_format' => 'Time Format',
    'number_format' => 'Number Format',
    'decimal_separator' => 'Decimal Separator',
    'thousands_separator' => 'Thousands Separator',
    'currency_symbol' => 'Currency Symbol',
    'currency_position' => 'Currency Position',
    'before' => 'Before',
    'after' => 'After',
    'left' => 'Left',
    'right' => 'Right',
    'center' => 'Center',
    'top' => 'Top',
    'bottom' => 'Bottom',
    'start' => 'Start',
    'end' => 'End',
    'beginning' => 'Beginning',
    'middle' => 'Middle',
    'final' => 'Final',
    'initial' => 'Initial',
    'primary' => 'Primary',
    'secondary' => 'Secondary',
    'tertiary' => 'Tertiary',
    'quaternary' => 'Quaternary',
    'quinary' => 'Quinary',
    'senary' => 'Senary',
    'septenary' => 'Septenary',
    'octonary' => 'Octonary',
    'nonary' => 'Nonary',
    'denary' => 'Denary',
];

