@extends('layouts.app')

@section('title', 'خريطة المصفوفة التنظيمية - ' . $department->name)

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4">
    <h2><i class="fas fa-sitemap me-2"></i>خريطة المصفوفة التنظيمية - {{ $department->name }}</h2>
    <div>
        <a href="{{ route('departments.show', $department) }}" class="btn btn-secondary">
            <i class="fas fa-arrow-right me-2"></i>العودة للقسم
        </a>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <!-- Department Header -->
        <div class="text-center mb-5">
            <div class="department-header">
                <div class="department-circle">
                    <i class="fas fa-building fa-2x"></i>
                </div>
                <h3 class="mt-3">{{ $department->name }}</h3>
                <p class="text-muted">{{ $department->description ?? 'لا يوجد وصف' }}</p>
            </div>
        </div>

        <!-- Organizational Chart Container -->
        <div class="org-chart-container">
            <div class="org-chart" id="orgChart" data-employees="{{ json_encode($department->users->load('role', 'manager')) }}">
                <!-- Chart will be generated by JavaScript -->
            </div>
        </div>

        <!-- Department Statistics -->
        <div class="row mt-5">
            <div class="col-md-3 text-center">
                <div class="stat-card">
                    <i class="fas fa-users fa-2x text-primary mb-2"></i>
                    <h4>{{ $department->users->count() }}</h4>
                    <p class="text-muted">إجمالي الموظفين</p>
                </div>
            </div>
            <div class="col-md-3 text-center">
                <div class="stat-card">
                    <i class="fas fa-user-tie fa-2x text-warning mb-2"></i>
                    <h4>{{ $department->users->where('role.slug', 'manager')->count() }}</h4>
                    <p class="text-muted">المديرين</p>
                </div>
            </div>
            <div class="col-md-3 text-center">
                <div class="stat-card">
                    <i class="fas fa-user fa-2x text-success mb-2"></i>
                    <h4>{{ $department->users->where('role.slug', 'employee')->count() }}</h4>
                    <p class="text-muted">الموظفين</p>
                </div>
            </div>
            <div class="col-md-3 text-center">
                <div class="stat-card">
                    <i class="fas fa-tasks fa-2x text-info mb-2"></i>
                    <h4>{{ $department->tasks->count() }}</h4>
                    <p class="text-muted">المهام</p>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Employee Details Modal -->
<div class="modal fade" id="employeeModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">تفاصيل الموظف</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body" id="employeeDetails">
                <!-- Employee details will be loaded here -->
            </div>
        </div>
    </div>
</div>

@endsection

@section('styles')
<link href="{{ asset('css/organizational-chart.css') }}" rel="stylesheet">
<style>
.org-chart-container {
    min-height: 600px;
    overflow-x: auto;
    overflow-y: auto;
    padding: 60px 20px;
    background: white;
    border-radius: 10px;
    margin: 20px 0;
    position: relative;
}

.org-chart {
    position: relative;
    width: 100%;
    height: 600px;
    background: white;
    border-radius: 10px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
}

.employee-node {
    position: absolute;
    text-align: center;
    cursor: pointer;
    transition: all 0.3s ease;
    z-index: 10;
    width: 120px;
    height: 120px;
}

.employee-node:hover {
    transform: translateY(-5px) scale(1.05);
    z-index: 20;
}

.employee-card {
    background: white;
    border-radius: 50%;
    padding: 0;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
    border: 4px solid #ffc107;
    transition: all 0.3s ease;
    width: 120px;
    height: 120px;
    position: relative;
    overflow: hidden;
    display: flex;
    align-items: center;
    justify-content: center;
}

.employee-card.manager {
    border-color: #ffc107;
    width: 140px;
    height: 140px;
}

.employee-circle {
    width: 100%;
    height: 100%;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
    background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
}

.employee-circle img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    border-radius: 50%;
}

.employee-circle .initials {
    font-size: 24px;
    font-weight: bold;
    color: #2c3e50;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
    background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
}

.employee-info {
    position: absolute;
    bottom: -50px;
    left: 50%;
    transform: translateX(-50%);
    text-align: center;
    white-space: nowrap;
    background: white;
    padding: 8px 12px;
    border-radius: 15px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    min-width: 100px;
    z-index: 15;
}

.employee-name {
    font-weight: bold;
    color: #2c3e50;
    font-size: 12px;
    margin-bottom: 2px;
}

.employee-title {
    color: #6c757d;
    font-size: 10px;
}

.connection-line {
    position: absolute;
    background: #28a745;
    z-index: 1;
    border-radius: 2px;
    box-shadow: 0 2px 4px rgba(40, 167, 69, 0.3);
}

.department-header {
    text-align: center;
    padding: 30px 0;
}

.department-circle {
    width: 80px;
    height: 80px;
    background: linear-gradient(135deg, #007bff 0%, #0056b3 100%);
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 0 auto;
    color: white;
    box-shadow: 0 4px 15px rgba(0,123,255,0.3);
}

.stat-card {
    background: white;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    transition: transform 0.3s ease;
}

.stat-card:hover {
    transform: translateY(-5px);
}
</style>
@endsection

@section('scripts')
<script src="{{ asset('js/organizational-chart.js') }}"></script>
@endsection
